// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn1BNeO27LG3uIWxGjpp_HB5SipLklw1I',
    appId: '1:12934972693:web:d0ad2d70f803515394951c',
    messagingSenderId: '12934972693',
    projectId: 'devproj-9c223',
    authDomain: 'devproj-9c223.firebaseapp.com',
    storageBucket: 'devproj-9c223.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHkgeRWu5bC44FmQf7sLY4tT-jIpoUI0I',
    appId: '1:12934972693:android:35eeb3c11856e0bb94951c',
    messagingSenderId: '12934972693',
    projectId: 'devproj-9c223',
    storageBucket: 'devproj-9c223.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPBzxXWxVT_KDtMyMa2KJZNa_qklu8bd4',
    appId: '1:12934972693:ios:1d0b79fbb3f349c694951c',
    messagingSenderId: '12934972693',
    projectId: 'devproj-9c223',
    storageBucket: 'devproj-9c223.appspot.com',
    androidClientId: '12934972693-e5gre3tddu47p16d5p2iris04gtb365n.apps.googleusercontent.com',
    iosClientId: '12934972693-16lvnokrulfp1f9dr7a40b8kd3r2kotr.apps.googleusercontent.com',
    iosBundleId: 'com.example.devproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPBzxXWxVT_KDtMyMa2KJZNa_qklu8bd4',
    appId: '1:12934972693:ios:1d0b79fbb3f349c694951c',
    messagingSenderId: '12934972693',
    projectId: 'devproj-9c223',
    storageBucket: 'devproj-9c223.appspot.com',
    androidClientId: '12934972693-e5gre3tddu47p16d5p2iris04gtb365n.apps.googleusercontent.com',
    iosClientId: '12934972693-16lvnokrulfp1f9dr7a40b8kd3r2kotr.apps.googleusercontent.com',
    iosBundleId: 'com.example.devproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn1BNeO27LG3uIWxGjpp_HB5SipLklw1I',
    appId: '1:12934972693:web:cdea9ba86d5df9d694951c',
    messagingSenderId: '12934972693',
    projectId: 'devproj-9c223',
    authDomain: 'devproj-9c223.firebaseapp.com',
    storageBucket: 'devproj-9c223.appspot.com',
  );
}
